spring.application.name=orar-personal

# 1. Conexiunea DIRECTA (Port 5432) - ocolim Pooler-ul
spring.datasource.url=jdbc:postgresql://db.gtqxfbyfymyldiegtrwr.supabase.co:5432/postgres?sslmode=require

# 2. La conexiunea directa, utilizatorul este simplu, fara cod
spring.datasource.username=postgres

# 3. Parola confirmata de tine
spring.datasource.password=7BmQLlXigGr9vhO6

# 4. Setari pentru crearea tabelului
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.address=0.0.0.0